import type { Corpus, Pair } from '../data/types';

/** Небольшой корпус для модульных тестов (формат как у pipeline). */
export const PAIR_BOOK: Pair = {
  id: 't-001',
  text_id: 't',
  position: 1,
  en: 'Anna wanted to find a book about China.',
  zh: '安娜想找一本关于中国的书。',
  ru: 'Анна хотела найти книгу о Китае.',
  alignment_type: '1-1-1',
  alignment_score: 0.8,
  alignment: { method: 'gale_church', en_zh: 0.8, en_ru: 0.9, low: false },
  annotations: {
    en: [
      {
        id: 'en1',
        kind: 'article',
        start: 20,
        end: 21,
        text: 'a',
        value: 'a',
        definite: false,
        head: { start: 22, end: 26, text: 'book', lemma: 'book', pos: 'NOUN', number: 'sing' },
        disputed: false,
      },
    ],
    zh: [
      {
        id: 'zh1',
        kind: 'classifier',
        start: 5,
        end: 6,
        text: '本',
        value: '本',
        pinyin: 'běn',
        type: 'именной',
        det: { start: 4, end: 5, text: '一' },
        head: { start: 11, end: 12, text: '书' },
        disputed: false,
      },
    ],
    ru: [
      {
        id: 'ru1',
        kind: 'case',
        start: 0,
        end: 4,
        text: 'Анна',
        lemma: 'анна',
        case: 'nomn',
        number: 'sing',
        gender: 'femn',
        animacy: 'anim',
        confidence: 1,
        ambiguous: false,
        disputed: false,
      },
      {
        id: 'ru2',
        kind: 'case',
        start: 19,
        end: 24,
        text: 'книгу',
        lemma: 'книга',
        case: 'accs',
        number: 'sing',
        gender: 'femn',
        animacy: 'inan',
        confidence: 1,
        ambiguous: false,
        disputed: false,
      },
      {
        id: 'ru3',
        kind: 'case',
        start: 27,
        end: 32,
        text: 'Китае',
        lemma: 'китай',
        case: 'loct',
        number: 'sing',
        gender: 'masc',
        animacy: 'inan',
        confidence: 1,
        ambiguous: false,
        disputed: false,
        prep: 'о',
      },
    ],
  },
  links: [{ en: [22, 26], zh: [11, 12], ru: [19, 24], score: 1 }],
  status: 'auto',
  llm_note: null,
  comment: '',
};

export const PAIR_TEA: Pair = {
  ...PAIR_BOOK,
  id: 't-002',
  position: 2,
  en: 'She ordered the tea.',
  zh: '她点了茶。',
  ru: 'Она заказала чай.',
  alignment_score: 0.2,
  alignment: { method: 'gale_church', en_zh: 0.2, en_ru: 0.9, low: true },
  annotations: {
    en: [
      {
        id: 'en1',
        kind: 'article',
        start: 12,
        end: 15,
        text: 'the',
        value: 'the',
        definite: true,
        head: { start: 16, end: 19, text: 'tea', lemma: 'tea', pos: 'NOUN', number: 'sing' },
        disputed: false,
      },
    ],
    zh: [],
    ru: [
      {
        id: 'ru1',
        kind: 'case',
        start: 13,
        end: 16,
        text: 'чай',
        lemma: 'чай',
        case: 'accs',
        number: 'sing',
        gender: 'masc',
        animacy: 'inan',
        confidence: 0.85,
        ambiguous: false,
        disputed: true,
      },
    ],
  },
  links: [],
  status: 'checked',
};

export const CORPUS: Corpus = {
  version: 1,
  generated_at: '2026-09-28T00:00:00+00:00',
  alignment_method: 'gale_church',
  low_score_threshold: 0.35,
  annotation_methods: { en: 'spacy', zh: 'jieba', ru: 'pymorphy3' },
  texts: [
    {
      id: 't',
      title: 'Test',
      title_ru: 'Тест',
      title_zh: '测试',
      source: 'тест',
      topic: 'тест',
      level: 'A2',
      author: '',
      pairs: 2,
    },
  ],
  classifiers: [{ value: '本', pinyin: 'běn', type: 'именной', gloss: 'книги', examples: ['书'] }],
  pairs: [PAIR_BOOK, PAIR_TEA],
};
